### PR TITLE
Add system_prompt

### PR DESCRIPTION
**Pull request by mybuddyandrew**
## All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](../blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

I've updated the wrap_prompt method to accommodate an optional system_prompt parameter. This change allows the method to prepend a given system prompt to the user prompt, enabling more versatile usage scenarios. For instance, it can be used to set a context or provide instructions when generating prompts for AI models.

The inclusion of the system_prompt enhances the functionality of the wrap_prompt method without altering its existing behavior when no system prompt is provided. This backward-compatible enhancement makes the method more flexible and applicable in a wider range of situations, such as automated generation of prompts for various AI roles or tasks.

### CODE REVIEW

**Comment by deikka** [comment]
Hi @alexrudall did you had a look? Will this PR be merged?

**Comment by alexrudall** [comment]
Hey @deikka @mybuddyandrew , I'm not sure about this one. Could you share a simple scenario where it would be helpful? I can't quite see it.

**Comment by deikka** [comment]
They recommend using a system prompt when using Claude 2.1 ([here](https://docs.anthropic.com/claude/docs/configuring-gpt-prompts-for-claude)) if using completions.

**Comment by alexrudall** [comment]
Thanks for this - closing as looks like the Text Completion endpoint is deprecated in favour of Messages.

**Pull request closed without merging**
