### PR TITLE
Implemented streaming and stream preprocessing

### PR DESCRIPTION
**Pull request by swombat**
https://github.com/alexrudall/anthropic/issues/7

## All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](../blob/main/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you added an explanation of what your changes do and why you'd like us to include them?

### CODE REVIEW

**Review by swombat — COMMENTED** [review]
Looks good - might even want to do `response=` to make it clear that `client.messages` returns a response?

**Comment by swombat** [comment]
@alexrudall ready to merge? 👀

**Comment by alexrudall** [comment]
Thanks so much @swombat !! A little different to the ruby-openai implementation, that may not be a bad thing, let's see how users find it :)

**Comment by alexrudall** [comment]
Released in [v0.3.0](https://github.com/alexrudall/anthropic/releases/tag/v0.3.0)

**Pull request merged**
